### ISSUE TITLE
[Cargon-branch]  In rotate, change "if" into "while"?

### ISSUE THREAD

**Issue by Soist** [team5308/Allen#3]
**Describe the bug**
I am not sure if it is a bug. 
It is in Cargon.cpp and Cargon branch. 

**If it is a build fail**
Actually, it did not fail, but I think there might be a small problem in line 57 to 66.
We need to keep comparing "diff" with 0, so "while" is suitable for this. 
To "if", it will just compare once, and then execute "catSpark -> Set(0);"

**Screenshots**
<img width="310" alt="screen shot 2019-01-29 at 12 02 43" src="https://user-images.githubusercontent.com/46078550/51883441-d45a7580-23bd-11e9-93f5-24e314f81f25.png">

**Comment by richcfno1** [comment]
In previous coding, using "while" seems cause the robot can only do the function rotate, and the driver will lose controlling to the robot. However, using "if" is available, because the function can be called for more times.
Still, I should add a "else if(diff == 0)" to "catSpark -> Set(0)".
We need a test to ensure that we can use "while" instead of "if".

**Comment by WuYuanhun** [comment]
> In previous coding, using "while" seems cause the robot can only do the function rotate, and the driver will lose controlling to the robot. However, using "if" is available, because the function can be called for more times.
> Still, I should add a "else if(diff == 0)" to "catSpark -> Set(0)".
> We need a test to ensure that we can use "while" instead of "if".

only if the sensor is offline, cause the losing control.
Try not to repeat calling the functions for many times, use a 'interrupt-able' instead

**Comment by richcfno1** [comment]
The "if" has been replaced with "while".
Should we close the issue?
